Add pulsating animation for imageview
mansi-cherry/Extensions pull request #1
Opened 2018-02-23 12:37 UTC by LuisBelo

Animating UIImageView using transform to change size of image, similar a heart (i think). Feedback me with problems or/and improvements.

2018-02-24 16:59 UTC, mansi-27 requested changes
Hey @LuisBelo 
🙌 This is really a very very cool  function 🙌 

I suggest some changes for this PR
1. Let's add this function under extenstion of UIImageView, so that we can directly call the function from any image (i.e myImageView.animate())
2. Let's give the function a more meaning-ful name like animateZoom(as it appears to animate the zoom in zoom out)
3. This is very important -> please remove the recursive call from the function, that will be more dyamic, as the developer would be free to call as many times he/she wants instead of constantly zooming in and out the image.

I have made changes in your function if you directly want to replace it,

```
extension UIImageView {
    func animateZoom() {
        
        UIView.animate(withDuration: 1, animations: {
            self.transform = CGAffineTransform(scaleX: 1.1, y: 1.1)
        }) { (success) in
            UIView.animate(withDuration: 1, animations: {
                self.transform = CGAffineTransform(scaleX: 0.7, y: 0.7)
            }, completion: nil)
            
        }
    }
}
```

So make sure to add another file "UIImageView+Extensions" and add it under the file.

Once again, kudos for the contribution 🙌

2018-04-08 06:11 UTC, mansi-27 approved these changes

2018-04-08 06:13 UTC, mansi-cherry commented
I have added changes as required. Hence closing it now 👍

2018-04-08 06:13 UTC, closed without merging

2018-04-08 10:46 UTC, LuisBelo commented
Thanks. Sorry, I had not forgotten that problem. I do not have time to solve this because I am in a android project and I have no MAC machine (for various reasons = D). Thank you!